name: Coveralls Test

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
       
      - name: Install poetry
        run: pipx install poetry==1.7.1

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install python dependencies
        run: poetry install
      
      - name: Test
        run: |
          poetry run pytest -v --cov=tfds --cov-report term-missing
          poetry run coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload coverage to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: poetry run coveralls