name: Formatting

on:
  push:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install poetry
      run: pipx install poetry==1.7.1

    - name: Install python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install python dependencies
      run: poetry install

    - name: Check formating
      run: poetry run black --check --diff --color .
